### ISSUE TITLE
Having issues with FastAPI server generation

### ISSUE THREAD

**Issue by saliksyed** [fern-api/fern#2898]
I am getting extremely flaky generations for a while and now they have completely stopped working. I always get the error message: `fernapi/fern-fastapi-server Failed to start job`

I ran ```fern generate --api internal-api --log-level debug```

And get the following, it seems like a socket hangs up on the backend... not sure what is going on:
```
fern generate --api internal-api --log-level debug
DEBUG 2024-02-06T01:27:57.175Z Running fern (fern-api@0.14.3)
INFO  2024-02-06T01:27:57.215Z Download ../shared Parsing...
DEBUG 2024-02-06T01:27:59.048Z [api]: fernapi/fern-typescript-browser-sdk Migrating IR from v23 to v22
DEBUG 2024-02-06T01:27:59.049Z [api]: fernapi/fern-typescript-browser-sdk Migrating IR from v22 to v21
DEBUG 2024-02-06T01:27:59.050Z [api]: fernapi/fern-typescript-browser-sdk Migrating IR from v21 to v20
DEBUG 2024-02-06T01:27:59.054Z [api]: fernapi/fern-fastapi-server Migrating IR from v23 to v22
DEBUG 2024-02-06T01:27:59.055Z [api]: fernapi/fern-fastapi-server Migrating IR from v22 to v21
DEBUG 2024-02-06T01:27:59.055Z [api]: fernapi/fern-fastapi-server Migrating IR from v21 to v20
DEBUG 2024-02-06T01:28:01.719Z [api]: fernapi/fern-typescript-browser-sdk Wrote IR to disk: /var/folders/db/c2yy6fp96077_7mx6lgn350r0000gn/T/tmp-18704-nztcT4xkU2n2
DEBUG 2024-02-06T01:28:01.720Z [api]: fernapi/fern-fastapi-server Wrote IR to disk: /var/folders/db/c2yy6fp96077_7mx6lgn350r0000gn/T/tmp-18704-uQT9WSh8uf6H
DEBUG 2024-02-06T01:28:11.676Z [api]: fernapi/fern-typescript-browser-sdk Job ID: 5aab1d80-c571-4c31-b5dc-156574732b66
DEBUG 2024-02-06T01:28:11.676Z [api]: fernapi/fern-typescript-browser-sdk Task ID: 3b113190-27ec-4e31-80a7-71206038a130
DEBUG 2024-02-06T01:28:11.738Z [api]: fernapi/fern-fastapi-server POST https://fiddle-coordinator.buildwithfern.com/api/remote-gen/jobs/8333b5b4-f1c5-439f-9cb7-397a0697d5a9/start failed with {"message":"socket hang up","name":"Error","stack":"Error: socket hang up\n    at connResetException (node:internal/errors:787:14)\n    at TLSSocket.socketCloseListener (node:_http_client:468:25)\n    at TLSSocket.emit (node:events:530:35)\n    at node:net:337:12\n    at TCP.done (node:_tls_wrap:657:7)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":null,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"multipart/form-data; boundary=--------------------------081927983768480603596734","User-Agent":"axios/0.27.2","content-type":"multipart/form-data; boundary=--------------------------081927983768480603596734"},"method":"post","url":"https://fiddle-coordinator.buildwithfern.com/api/remote-gen/jobs/8333b5b4-f1c5-439f-9cb7-397a0697d5a9/start","data":{"_overheadLength":103,"_valueLength":2442429,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------081927983768480603596734","_events":{},"_eventsCount":1}},"code":"ECONNRESET","status":null}
ERROR 2024-02-06T01:28:11.739Z [api]: fernapi/fern-fastapi-server Failed to start job
DEBUG 2024-02-06T01:28:11.771Z [api]: fernapi/fern-fastapi-server Error
                                                                      at logErrorMessage (/Users/saliksyed/.npm/_npx/e3380027af34bc57/node_modules/fern-api/bundle.cjs:534200:56)
                                                                      at InteractiveTaskContextImpl.failWithoutThrowing (/Users/saliksyed/.npm/_npx/e3380027af34bc57/node_modules/fern-api/bundle.cjs:534259:5)
                                                                      at InteractiveTaskContextImpl.failAndThrow (/Users/saliksyed/.npm/_npx/e3380027af34bc57/node_modules/fern-api/bundle.cjs:534254:10)
                                                                      at startJob (/Users/saliksyed/.npm/_npx/e3380027af34bc57/node_modules/fern-api/bundle.cjs:549758:13)
                                                                      at async createAndStartJob (/Users/saliksyed/.npm/_npx/e3380027af34bc57/node_modules/fern-api/bundle.cjs:549686:3)
                                                                      at async runRemoteGenerationForGenerator (/Users/saliksyed/.npm/_npx/e3380027af34bc57/node_modules/fern-api/bundle.cjs:549957:15)
                                                                      at async /Users/saliksyed/.npm/_npx/e3380027af34bc57/node_modules/fern-api/bundle.cjs:550016:5
                                                                      at async TaskContextImpl.runInteractiveTask (/Users/saliksyed/.npm/_npx/e3380027af34bc57/node_modules/fern-api/bundle.cjs:534309:7)
                                                                      at async Promise.all (index 0)
                                                                      at async runRemoteGenerationForWorkspace (/Users/saliksyed/.npm/_npx/e3380027af34bc57/node_modules/fern-api/bundle.cjs:550027:19)

```

**Comment by armandobelardo** [comment]
@saliksyed generation should have improved performance and stability now, please feel free to comment back/re-open this issue if it's still a problem for you!
