### ISSUE TITLE
Updating to `0.18.1` throws error when running `fern generate --docs`

### ISSUE THREAD

**Issue by homanp** [fern-api/fern#3030]
### Describe the bug
After updating the CLI to `v0.18.1` I'm getting the following error: 

```
Could not find original type declaration for property: success
DEBUG 2024-02-21T18:50:34.046Z [docs]: https://superagent.docs.buildwithfern.com Error: Could not find original type declaration for property: success
                                                                                     at /opt/homebrew/lib/node_modules/fern-api/bundle.cjs:804896:15
                                                                                     at Array.reduce (<anonymous>)
                                                                                     at convertObject3 (/opt/homebrew/lib/node_modules/fern-api/bundle.cjs:804887:72)
                                                                                     at Object.object (/opt/homebrew/lib/node_modules/fern-api/bundle.cjs:804601:14)
                                                                                     at visitRawTypeDeclaration (/opt/homebrew/lib/node_modules/fern-api/bundle.cjs:786157:20)
                                                                                     at convertTypeExample (/opt/homebrew/lib/node_modules/fern-api/bundle.cjs:804586:10)
                                                                                     at Object.named (/opt/homebrew/lib/node_modules/fern-api/bundle.cjs:804796:16)
                                                                                     at visitRawTypeReference (/opt/homebrew/lib/node_modules/fern-api/bundle.cjs:787539:18)
                                                                                     at convertTypeReferenceExample (/opt/homebrew/lib/node_modules/fern-api/bundle.cjs:804697:17)
                                                                                     at convertExampleResponseBody (/opt/homebrew/lib/node_modules/fern-api/bundle.cjs:805342:10)
```
### To reproduce

1. Upgrade to 0.18.1
2. Run the command `fern generate --docs`

### Expected behavior
Expected to not throw

### Version
0.18.1

**Comment by armandobelardo** [comment]
@homanp closing this out as I believe this issue has been resolved on the latest version of the CLI, but please ping if not!
