### ISSUE TITLE
Cli Zod failures have obnoxious error messages 

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#382]
```
]
    at handleResult (/Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:6876:23)
    at ZodObject.safeParseAsync (/Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:7013:16)
    at async ZodObject.parseAsync (/Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:6991:24)
    at async loadWorkspaceDefinitionSchema (/Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:9379:12)
    at async loadWorkspaceDefinition (/Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:9382:23)
    at async parseAndValidateWorkspace (/Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:13997:33)
    at async Promise.all (index 8)
    at async validateWorkspaces (/Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:16780:5) {
  issues: [
    {
      code: ‘unrecognized_keys’,
      keys: [ ‘output’ ],
      path: [ ‘generators’, 0 ],
      message: “Unrecognized key(s) in object: ‘output’”
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)]
}```

**Comment by zachkirsch** [comment]
+1

**Comment by dannysheridan** [comment]
+1 https://birchsolutions.slack.com/archives/C02AR20BL7P/p1665884082169799
