### ISSUE TITLE
Ugly error for bad import

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#406]
```
/Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:13870
                        throw new Error("Encountered unexpected file: " + namedType.relativeFilePath);
                              ^

Error: Encountered unexpected file: connection/commons.yml
    at /Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:13870:31
    at Array.reduce (<anonymous>)
    at typeReference (/Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:13867:35)
    at Object.visit [as typeReference] (/Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:13743:50)
    at Object.properties (/Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:13599:58)
    at visitObject (/Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:12747:27)
    at Object.object (/Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:13581:19)
    at visitRawTypeDeclaration (/Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:12607:24)
    at visitTypeDeclaration (/Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:13566:11)
    at visitTypeDeclarations (/Users/dsheridan/.nvm/versions/node/v18.1.0/lib/node_modules/fern-api/bundle.js:13562:15)```

**Comment by dannysheridan** [comment]
@zachkirsch looks like your validation rule doesn't get to run b/c we throw an error beforehand
